export enum PERMISSION_IDS {
    MANAGE_PROJECTS = 'MANAGE_PROJECTS',
    MANAGE_USERS = 'MANAGE_USERS',
    MANAGE_COMMENTS = 'MANAGE_COMMENTS',
    MANAGE_ISSUES = 'MANAGE_ISSUES',
    MANAGE_DOCS = 'MANAGE_DOCS',
}