export const IssueSeed = [
    {
        id: 1,
        name: 'IST-1',
        verboseName: 'Backend REST service',
        type: 'Epic',
        description: 'Create REST service with these endpoints...',
        status: 'In progress',
        priority: 1,
        hoursEstimated: 16,
        hoursRemaining: 16,
        hoursSpent: 0,
        gitLink: null,
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [2],
        parentIssue: null,
        created: new Date(),
        edited: new Date(),
        createdByUser: 1,
        editedByUser: 1
    },
    {
        id: 2,
        name: 'IST-2',
        verboseName: 'Create controller layer',
        type: 'Issue',
        description: 'Create controller layer with this specification',
        status: 'In progress',
        priority: 2,
        hoursEstimated: 8,
        hoursRemaining: 8,
        hoursSpent: 0,
        gitLink: null,
        // commentPosts: [1],
        project: 1,
        user: 1,
        childIssues: [3],
        parentIssue: 1,
        created: new Date(),
        edited: new Date(),
        createdByUser: 1,
        editedByUser: 1
    },
    {
        id: 3,
        name: 'IST-3',
        verboseName: 'Create register endpoint',
        type: 'Issue',
        description: 'Create register endpoint method with these parameters..',
        status: 'Open',
        priority: 3,
        hoursEstimated: 2,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: null,
        commentPosts: [2],
        project: 1,
        user: 2,
        childIssues: [],
        parentIssue: 2,
        created: new Date(),
        createdByUser: 1,
    },
]