import { ISSUE_STATUSES } from "src/constant/issue-status.enum";
import { ISSUE_TYPES } from "src/constant/issue-type.enum";

export const IssueSeed = [
    // STARSHIP
    {
        id: 1,
        name: 'SN20-1',
        verboseName: 'Backend REST service',
        type: ISSUE_TYPES.EPIC,
        description: 'Create REST service with these endpoints...',
        status: ISSUE_STATUSES.OPEN,
        priority: 1,
        hoursEstimated: 16.5,
        hoursRemaining: 16.5,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: null,
        childIssues: [2],
        parentIssue: null,
        created: new Date(),
        edited: new Date(),
        resolved: null,
        createdByUser: 1,
        editedByUser: 1
    },
    {
        id: 2,
        name: 'SN20-2',
        verboseName: 'Create controller layer',
        type: ISSUE_TYPES.TASK,
        description: 'Create controller layer with this specification',
        status: ISSUE_STATUSES.IN_PROGRESS,
        priority: 2,
        hoursEstimated: 8,
        hoursRemaining: 5,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        // commentPosts: [1],
        project: 2,
        user: 1,
        childIssues: [3],
        parentIssue: 1,
        created: new Date(),
        edited: new Date(),
        resolved: null,
        createdByUser: 1,
        editedByUser: 1
    },
    {
        id: 3,
        name: 'SN20-3',
        verboseName: 'Create register endpoint',
        type: ISSUE_TYPES.TASK,
        description: 'Create register endpoint method with these parameters..',
        status: ISSUE_STATUSES.NEEDS_INFORMATION,
        priority: 3,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 12,
        gitLink: 'https://github.com/plsve',
        commentPosts: [2],
        project: 2,
        user: 2,
        childIssues: [],
        parentIssue: 2,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 4,
        name: 'SN20-4',
        verboseName: 'Fix delete endpoint',
        type: ISSUE_TYPES.BUG,
        description: 'Fix delete endpoint we talked about, here\'s what we\'ve agreed on..',
        status: ISSUE_STATUSES.CANCELED,
        priority: 4,
        hoursEstimated: 12,
        hoursRemaining: 6,
        hoursSpent: 20,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: 2,
        childIssues: [],
        parentIssue: 2,
        created: new Date(),
        createdByUser: 1,
    },
    {
        id: 5,
        name: 'ISF-5',
        verboseName: 'Fix delete endpoint',
        type: ISSUE_TYPES.TASK,
        description: 'Create register endpoint method with these parameters..',
        status: ISSUE_STATUSES.DONE,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: 1,
        childIssues: [],
        parentIssue: null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 6,
        name: 'SN20-6',
        verboseName: 'Issue without epic',
        type: ISSUE_TYPES.TASK,
        description: 'This is a test issue description',
        status: ISSUE_STATUSES.OPEN,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: 1,
        childIssues: [7],
        parentIssue: null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 7,
        name: 'SN20-7',
        verboseName: 'Child issue without epic',
        type: ISSUE_TYPES.TASK,
        description: 'This is a test child issue description',
        status: ISSUE_STATUSES.OPEN,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: 1,
        childIssues: [],
        parentIssue: 6,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 8,
        name: 'SN20-8',
        verboseName: 'Build mars rover',
        type: ISSUE_TYPES.EPIC,
        description: 'This is a test child issue description',
        status: ISSUE_STATUSES.OPEN,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: null,
        childIssues: [9, 10],
        parentIssue:  null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 9,
        name: 'SN20-9',
        verboseName: 'Forge a wheel',
        type: ISSUE_TYPES.TASK,
        description: 'This is a test child issue description',
        status: ISSUE_STATUSES.OPEN,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: 1,
        childIssues: [],
        parentIssue:  8,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 10,
        name: 'SN20-10',
        verboseName: 'Trunk is not working',
        type: ISSUE_TYPES.BUG,
        description: 'This is a test child issue description',
        status: ISSUE_STATUSES.IN_PROGRESS,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: 1,
        childIssues: [],
        parentIssue:  8,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 11,
        name: 'SN20-11',
        verboseName: 'Empty epic',
        type: ISSUE_TYPES.EPIC,
        description: 'This is a test child issue description',
        status: ISSUE_STATUSES.OPEN,
        priority: 5,
        hoursEstimated: 10,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 2,
        user: null,
        childIssues: [],
        parentIssue:  null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },

    // ISSUE TRACKER

    {
        id: 12,
        name: 'IST-1',
        verboseName: 'Frontend',
        type: ISSUE_TYPES.EPIC,
        description: 'Everything related to Frontend',
        status: ISSUE_STATUSES.IN_PROGRESS,
        priority: 5,
        hoursEstimated: 200,
        hoursRemaining: 120,
        hoursSpent: 80,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },    
    {
        id: 13,
        name: 'IST-2',
        verboseName: 'Backend',
        type: ISSUE_TYPES.EPIC,
        description: 'Everything related to Backend',
        status: ISSUE_STATUSES.IN_PROGRESS,
        priority: 5,
        hoursEstimated: 160,
        hoursRemaining: 20,
        hoursSpent: 140,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 14,
        name: 'IST-3',
        verboseName: 'Database',
        type: ISSUE_TYPES.EPIC,
        description: 'Everything related to Database',
        status: ISSUE_STATUSES.IN_PROGRESS,
        priority: 5,
        hoursEstimated: 80,
        hoursRemaining: 10,
        hoursSpent: 70,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 15,
        name: 'IST-4',
        verboseName: 'DevOps',
        type: ISSUE_TYPES.EPIC,
        description: 'Everything related to DevOps',
        status: ISSUE_STATUSES.IN_PROGRESS,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 1,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 2,
        childIssues: [],
        parentIssue:  null,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },// ============ FRONTEND TASKS ============
    {
        id: 16,
        name: 'IST-5',
        verboseName: 'Init project',
        type: ISSUE_TYPES.TASK,
        description: 'Create empty project',
        status: ISSUE_STATUSES.DONE,
        priority: 5,
        hoursEstimated: 2,
        hoursRemaining: 0,
        hoursSpent: 1,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 17,
        name: 'IST-6',
        verboseName: 'Design Angular theme',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 4,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 18,
        name: 'IST-7',
        verboseName: 'Design top bar graphic',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 3,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 3,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 19,
        name: 'IST-8',
        verboseName: 'Design side bar graphic',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 3,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 3,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 20,
        name: 'IST-9',
        verboseName: 'Design main logo',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 3,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 21,
        name: 'IST-10',
        verboseName: 'Implement main layout',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 4,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 22,
        name: 'IST-11',
        verboseName: 'Implement top bar',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 4,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 23,
        name: 'IST-12',
        verboseName: 'Implement side bar',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 6,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 24,
        name: 'IST-13',
        verboseName: 'Implement Board page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 8,
        hoursRemaining: 0,
        hoursSpent: 8,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 25,
        name: 'IST-14',
        verboseName: 'Implement Kanban board component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 6,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 26,
        name: 'IST-15',
        verboseName: 'Implement Issues page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 6,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 27,
        name: 'IST-16',
        verboseName: 'Implement Issue sorting',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 3,
        hoursRemaining: 0,
        hoursSpent: 3,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 28,
        name: 'IST-17',
        verboseName: 'Implement Issue detail page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 5,
        hoursRemaining: 0,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 29,
        name: 'IST-18',
        verboseName: 'Implement Issue detail edit mode',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 5,
        hoursRemaining: 0,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 30,
        name: 'IST-19',
        verboseName: 'Implement Hour graph component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 3,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 31,
        name: 'IST-20',
        verboseName: 'Implement Issue handle component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 3,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 32,
        name: 'IST-21',
        verboseName: 'Implement User handle component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 3,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 33,
        name: 'IST-22',
        verboseName: 'Implement Priority badge component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 3,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 34,
        name: 'IST-23',
        verboseName: 'Implement Status badge component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 3,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 35,
        name: 'IST-24',
        verboseName: 'Implement Type badge component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 3,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 36,
        name: 'IST-25',
        verboseName: 'Implement Issue dropdown formfield',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 6,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 37,
        name: 'IST-26',
        verboseName: 'Implement Projects dropdown component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 5,
        hoursRemaining: 0,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 38,
        name: 'IST-27',
        verboseName: 'Implement Filters component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 5,
        hoursRemaining: 0,
        hoursSpent: 7,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 39,
        name: 'IST-28',
        verboseName: 'Implement Filter service',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 40,
        name: 'IST-29',
        verboseName: 'Implement Routing module',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 41,
        name: 'IST-30',
        verboseName: 'Implement Auth service',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 4,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 42,
        name: 'IST-31',
        verboseName: 'Implement Request interceptor',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 2,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 43,
        name: 'IST-32',
        verboseName: 'Implement Issue service',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 6,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 44,
        name: 'IST-33',
        verboseName: 'Implement Project service',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 45,
        name: 'IST-34',
        verboseName: 'Implement User service',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 6,
        hoursRemaining: 0,
        hoursSpent: 5,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 46,
        name: 'IST-35',
        verboseName: 'Implement Kanban drag service',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.DONE,
        priority: 4,
        hoursEstimated: 4,
        hoursRemaining: 0,
        hoursSpent: 2,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 47,
        name: 'IST-36',
        verboseName: 'Implement Create section',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 8,
        hoursRemaining: 8,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 48,
        name: 'IST-37',
        verboseName: 'Implement Breadcrumbs component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 6,
        hoursRemaining: 6,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 49,
        name: 'IST-38',
        verboseName: 'Implement Recent dropdown component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 6,
        hoursRemaining: 6,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 50,
        name: 'IST-39',
        verboseName: 'Implement Log in/Log out component',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 6,
        hoursRemaining: 6,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 51,
        name: 'IST-40',
        verboseName: 'Implement User preferences section',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 5,
        hoursRemaining: 5,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 52,
        name: 'IST-41',
        verboseName: 'Implement File attachments section',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 4,
        hoursRemaining: 4,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 53,
        name: 'IST-42',
        verboseName: 'Implement People page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 6,
        hoursRemaining: 6,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 54,
        name: 'IST-43',
        verboseName: 'Implement Docs page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 8,
        hoursRemaining: 8,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 55,
        name: 'IST-44',
        verboseName: 'Implement Logs page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 8,
        hoursRemaining: 8,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 56,
        name: 'IST-45',
        verboseName: 'Implement Statistics page',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 8,
        hoursRemaining: 8,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 57,
        name: 'IST-46',
        verboseName: 'Implement i18n',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 6,
        hoursRemaining: 6,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    },
    {
        id: 58,
        name: 'IST-47',
        verboseName: 'Implement Tests',
        type: ISSUE_TYPES.TASK,
        description: '',
        status: ISSUE_STATUSES.OPEN,
        priority: 3,
        hoursEstimated: 24,
        hoursRemaining: 24,
        hoursSpent: 0,
        gitLink: 'https://github.com/plsve',
        commentPosts: [],
        project: 1,
        user: 1,
        childIssues: [],
        parentIssue:  12,
        created: new Date(),
        resolved: new Date(),
        createdByUser: 1,
    }, // ============ BACKEND TASKS
    
]