export const TaskSeed = [
    {
        id: 1,
        name: 'Issue-Tracker-1',
        verboseName: 'Backend REST service',
        type: 'Epic',
        description: 'Create REST service with these endpoints...',
        status: 'In progress',
        priority: 1,
        hoursEstimated: 16,
        hoursRemaining: 16,
        hoursSpent: 0,
        gitLink: null,
        commentPosts: [],
        project: 1,
        user: 1,
        childTasks: [2],
        parentTask: null
    },
    {
        id: 2,
        name: 'Issue-Tracker-2',
        verboseName: 'Create controller layer',
        type: 'Task',
        description: 'Create controller layer with this specification',
        status: 'In progress',
        priority: 2,
        hoursEstimated: 8,
        hoursRemaining: 8,
        hoursSpent: 0,
        gitLink: null,
        // commentPosts: [1],
        project: 1,
        user: 1,
        childTasks: [3],
        parentTask: 1
    },
    {
        id: 3,
        name: 'Issue-Tracker-3',
        verboseName: 'Create register endpoint',
        type: 'Task',
        description: 'Create register endpoint method with these parameters..',
        status: 'Open',
        priority: 3,
        hoursEstimated: 2,
        hoursRemaining: 2,
        hoursSpent: 5,
        gitLink: null,
        commentPosts: [2],
        project: 1,
        user: 2,
        childTasks: [],
        parentTask: 2
    },
]